name: Build

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare_maven_build
      - name: Build
        run: mvn ${MAVEN_CLI_ARGS} test-compile
      - uses: ./.github/actions/upload_intermediate_artifacts

  test:
    runs-on: "ubuntu-latest"
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare_maven_build
      - uses: ./.github/actions/download_intermediate_artifacts
      - name: Run unit tests
        run: mvn ${MAVEN_CLI_ARGS} -DskipITs test
      - uses: ./.github/actions/upload_intermediate_artifacts
        with:
          artifact-name: unit-test-results
          source-path: ./target/surefire-reports/
      - uses: ./.github/actions/upload_intermediate_artifacts
        with:
          artifact-name: test-coverage
          source-path: ./target/*.exec

  integration-test:
    runs-on: "ubuntu-latest"
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare_maven_build
      - uses: ./.github/actions/download_intermediate_artifacts
      - name: Run integration tests
        run: mvn ${MAVEN_CLI_ARGS} -DskipUnitTests verify
      - uses: ./.github/actions/upload_intermediate_artifacts
        with:
          artifact-name: integration-test-results
          source-path: ./target/failsafe-reports/
      - uses: ./.github/actions/upload_intermediate_artifacts
        with:
          artifact-name: integration-test-coverage
          source-path: ./target/*.exec

  coverage-report:
    runs-on: "ubuntu-latest"
    needs: [ test, integration-test ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare_maven_build
      - uses: ./.github/actions/download_intermediate_artifacts
      - uses: ./.github/actions/download_intermediate_artifacts
        with:
          artifact-name: test-coverage
          destination-folder: ./target
      - uses: ./.github/actions/download_intermediate_artifacts
        with:
          artifact-name: integration-test-coverage
          destination-folder: ./target
      - name: Generate coverage report
        run: mvn ${MAVEN_CLI_ARGS} verify -Dmaven.main.skip=true -Dmaven.test.skip=true
      - uses: ./.github/actions/upload_intermediate_artifacts
        with:
          artifact-name: coverage-report
          source-path: ./target/site/jacoco-aggregate/

  quality-check:
    needs: coverage-report
    uses: ./.github/workflows/02-sonarcloud.yml
    permissions:
      contents: read
      pull-requests: write
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
