name: Build

env:
  MAVEN_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
  MAVEN_CLI_OPTS: "-B -ntp -fae -T 2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dmaven.install.skip=true -Dmaven.compiler.useIncrementalCompilation=false -DlastModGranularityMs=1000000"
  JACOCO_MAVEN_PLUGIN: "org.jacoco:jacoco-maven-plugin:0.8.13"

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare_maven_build
      - name: Build
        run: mvn ${MAVEN_CLI_OPTS} test-compile
      - uses: ./.github/actions/upload_intermediate_artifacts

  test:
    runs-on: "ubuntu-latest"
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare_maven_build
      - uses: ./.github/actions/download_intermediate_artifacts
      - name: Run unit tests
        run: mvn ${MAVEN_CLI_OPTS} -DskipITs=true ${JACOCO_MAVEN_PLUGIN}:prepare-agent test ${JACOCO_MAVEN_PLUGIN}:report
      - uses: ./.github/actions/upload_intermediate_artifacts
        with:
          artifact-name: unit-test-results
          source-folder: ./target/surefire-reports/

  integration-test:
    runs-on: "ubuntu-latest"
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare_maven_build
      - uses: ./.github/actions/download_intermediate_artifacts
      - name: Run integration tests
        run: mvn ${MAVEN_CLI_OPTS} -DskipTests=true ${JACOCO_MAVEN_PLUGIN}:prepare-agent verify ${JACOCO_MAVEN_PLUGIN}:report
      - uses: ./.github/actions/upload_intermediate_artifacts
        with:
          artifact-name: integration-test-results
          source-folder: ./target/failsafe-reports/
      - uses: ./.github/actions/upload_intermediate_artifacts
        with:
          artifact-name: coverage-reports
          source-folder: ./target/site/jacoco/

  quality-check:
    needs: [test, integration-test]
    uses: ./.github/workflows/02-sonarcloud.yml
    secrets: inherit
