name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

permissions:
  contents: read
  packages: write

jobs:
  deploy-snapshot:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare_maven_build
      - uses: ./.github/actions/download_intermediate_artifacts
      - name: Deploy snapshot
        run: mvn ${MAVEN_CLI_ARGS} -DskipTests deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
