name: Release

on:
  push:
    branches:
      - "feature/*"

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  preflight:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.read_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare_maven_build
      - name: Read version from pom.xml
        id: read_version
        run: echo "version=$(mvn -q -DforceStdout -Dchangelist= -Dexpression=project.version help:evaluate)" >> "$GITHUB_OUTPUT"

  build:
    needs: preflight
    uses: ./.github/workflows/01-build.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  release:
    needs: [preflight, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare_maven_build
      - name: Debug output of Build workflow
        run: |
          echo "Run-id of compile step: ${{ needs.build.outputs.run-id }}"
      - uses: ./.github/actions/download_intermediate_artifacts
      - name: Verify non-snapshot version
        run: |
          VERSION="${{ needs.preflight.outputs.VERSION }}"
          if [[ "$VERSION" == *"-SNAPSHOT" ]]; then
            echo "This workflow must deploy a non-snapshot version. Current version is: $VERSION"
            exit 1
          fi
      - uses: ./.github/actions/download_intermediate_artifacts
      - name: Deploy release artifacts (GitHub Packages)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn ${MAVEN_CLI_OPTS} -Dchangelist= -DskipTests package
